<template lang="html">
  <div class="">
    <HeadingSection class="mt-8 mb-16" title="Nossos Clientes" />
    <main class="container mx-auto flex flex-wrap">
      <div v-for="cliente in clientes" :key="cliente.ID" class="w-1/2 md:w-1/4 p-2">
        <div class="bg-white shadow-lg">
          <img class="w-full" :src="cliente['Image URL']" alt="">
          <h6 class="text-center py-4 text-lg text-astronaut">{{ cliente.Title }}</h6>
        </div>
      </div>
    </main>
  </div>
</template>

<script>
import HeadingSection from "~/components/HeadingSection.vue"

export default {
  name: 'TodosOsProdutos',
  components: {
    HeadingSection,
  },
  data: function (){
    return {
      clientes: [
  {
    "ID": 139,
    "Title": "La Belle",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-30",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/le-belle/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/lebelle.jpg",
    "Image Title": "lebelle",
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/lebelle.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "le-belle",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-30",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 141,
    "Title": "Copy Art",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-30",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/copy-art/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/68.jpg",
    "Image Title": 68,
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "copy-art",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-30",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 144,
    "Title": "Oral Sin",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-30",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/oral-sin/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/oralsin.jpg",
    "Image Title": "oralsin",
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/oralsin.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "oral-sin",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-30",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 146,
    "Title": "Cartório de Registro Civil",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-30",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/cartorio-de-registro-civil/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/cartorio.jpg",
    "Image Title": "cartorio",
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/cartorio.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "cartorio-de-registro-civil",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-30",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 148,
    "Title": "Barbacoa Espetaria - Rondon",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-30",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/barbacoa-espetaria-rondon/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/barbacoa-rondon.jpg",
    "Image Title": "barbacoa rondon",
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/barbacoa-rondon.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "barbacoa-espetaria-rondon",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-30",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 150,
    "Title": "CDL Uberlândia",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-30",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/cdl-uberlandia/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/cdl_udia.jpg",
    "Image Title": "cdl_udia",
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/cdl_udia.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "cdl-uberlandia",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-30",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 152,
    "Title": "Schmidt",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-30",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/schmidt/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/schmidt.jpg",
    "Image Title": "schmidt",
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/schmidt.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "schmidt",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-30",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 154,
    "Title": "CDL Araguari",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-30",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/cdl-araguari/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/cdl_araguari.jpg",
    "Image Title": "cdl_araguari",
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/cdl_araguari.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "cdl-araguari",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-30",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 156,
    "Title": "Algar Agro",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-30",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/algar-agro/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/algar_agro.jpg",
    "Image Title": "algar_agro",
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/algar_agro.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "algar-agro",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-30",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 158,
    "Title": "Câmara Municipal de Monte Alegre de Minas",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-30",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/camara-municipal-de-monte-alegre-de-minas/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/cam_mun_monte_alegre.jpg",
    "Image Title": "cam_mun_monte_alegre",
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/cam_mun_monte_alegre.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "camara-municipal-de-monte-alegre-de-minas",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-30",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 160,
    "Title": "Ativa",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-30",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/ativa/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/ativa.jpg",
    "Image Title": "ativa",
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/ativa.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "ativa",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-30",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 162,
    "Title": "OAB",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-30",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/oab/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/oab.jpg",
    "Image Title": "oab",
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/oab.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "oab",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-30",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 164,
    "Title": "Barbacoa Espetaria - Sta Mônica",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-30",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/barbacoa-espetaria-sta-monica/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/barbacoa-sta-monica.jpg",
    "Image Title": "barbacoa sta monica",
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/barbacoa-sta-monica.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "barbacoa-espetaria-sta-monica",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-30",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 166,
    "Title": "Sicoob",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-31",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/sicoob/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/sicoob.jpg",
    "Image Title": "sicoob",
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/sicoob.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "sicoob",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-31",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 168,
    "Title": "Stopark",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-31",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/stopark/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/stopark.jpg",
    "Image Title": "stopark",
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/stopark.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "stopark",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-31",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 170,
    "Title": "Multi",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-31",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/multi/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/multi.jpg",
    "Image Title": "multi",
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/multi.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "multi",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-31",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 172,
    "Title": "Rotina",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-31",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/rotina/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/rotina.jpg",
    "Image Title": "rotina",
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/rotina.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "rotina",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-31",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 174,
    "Title": "Mega",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-31",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/mega/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/mega-sorvetes.jpg",
    "Image Title": "mega sorvetes",
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/mega-sorvetes.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "mega",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-31",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 176,
    "Title": "Sicoob Creditril",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-31",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/sicoob-creditril/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/sicoob_creditril.jpg",
    "Image Title": "sicoob_creditril",
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/sicoob_creditril.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "sicoob-creditril",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-31",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 178,
    "Title": "London",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-31",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/london/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/london.jpg",
    "Image Title": "london",
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/london.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "london",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-31",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 182,
    "Title": "Açai Nativo",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-31",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/acai-nativo/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/acai_nativo.jpg",
    "Image Title": "acai_nativo",
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/acai_nativo.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "acai-nativo",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-31",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 184,
    "Title": "CCPR",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-31",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/ccpr/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/ccpr.jpg",
    "Image Title": "ccpr",
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/ccpr.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "ccpr",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-31",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 186,
    "Title": "Sicoob Aracredi",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-31",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/sicoob-aracredi/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/sicoob_aracredi.jpg",
    "Image Title": "sicoob_aracredi",
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/sicoob_aracredi.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "sicoob-aracredi",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-31",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 188,
    "Title": "Sicoob Cred Ufu",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-31",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/sicoob-cred-ufu/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/sicoob_cred_-ufu.jpg",
    "Image Title": "sicoob_cred_ ufu",
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/sicoob_cred_-ufu.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "sicoob-cred-ufu",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-31",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 190,
    "Title": "Modulo",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-31",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/modulo/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/modulo.jpg",
    "Image Title": "modulo",
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/modulo.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "modulo",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-31",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 192,
    "Title": "Clima",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-31",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/clima/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/clima.jpg",
    "Image Title": "clima",
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/clima.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "clima",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-31",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 194,
    "Title": "All Vita",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-31",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/all-vita/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/allvita.jpg",
    "Image Title": "allvita",
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/allvita.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "all-vita",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-31",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 196,
    "Title": "IOSG",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-31",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/iosg/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/iosg.jpg",
    "Image Title": "iosg",
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/iosg.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "iosg",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-31",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 198,
    "Title": "Itambé",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-31",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/itambe/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/itambe.jpg",
    "Image Title": "itambe",
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/itambe.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "itambe",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-31",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 200,
    "Title": "DN Prática",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-31",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/dn-pratica/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/dn-pratica.jpg",
    "Image Title": "dn pratica",
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/dn-pratica.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "dn-pratica",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-31",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 202,
    "Title": "Carlton Plaza",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-31",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/carlton-plaza/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/carlton-plaza.jpg",
    "Image Title": "carlton plaza",
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/carlton-plaza.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "carlton-plaza",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-31",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 204,
    "Title": "Drogalider",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-31",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/drogalider/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/droga-lider.jpg",
    "Image Title": "droga lider",
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/droga-lider.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "drogalider",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-31",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 206,
    "Title": "Dede Agro",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-31",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/dede-agro/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/dede-agro.jpg",
    "Image Title": "dede agro",
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/dede-agro.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "dede-agro",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-31",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 208,
    "Title": "Fertigran",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-31",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/fertigran/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/fertigran.jpg",
    "Image Title": "fertigran",
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/fertigran.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "fertigran",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-31",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 210,
    "Title": "Fundação CDL Uberlândia",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-31",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/fundacao-cdl-uberlandia/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/fundacao-cdl.jpg",
    "Image Title": "fundacao cdl",
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/fundacao-cdl.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "fundacao-cdl-uberlandia",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-31",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 212,
    "Title": "Uberlândia Shopping",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-31",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/uberlandia-shopping/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/udia-shopping.jpg",
    "Image Title": "udia shopping",
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/udia-shopping.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "uberlandia-shopping",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-31",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 214,
    "Title": "Algar Tech",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-31",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/algar-tech/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/algar-tech.jpg",
    "Image Title": "algar tech",
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/algar-tech.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "algar-tech",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-31",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 216,
    "Title": "Habitual",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-31",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/habitual/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/habitual.jpg",
    "Image Title": "habitual",
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/habitual.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "habitual",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-31",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 218,
    "Title": "Lev",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-31",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/lev/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/lev.jpg",
    "Image Title": "lev",
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/lev.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "lev",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-31",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 220,
    "Title": "H Olhos",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-31",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/h-olhos/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/holhos.jpg",
    "Image Title": "holhos",
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/holhos.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "h-olhos",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-31",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 222,
    "Title": "Paula Decorações",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-31",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/paula-decoracoes/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/paula-decor.jpg",
    "Image Title": "paula decor",
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/paula-decor.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "paula-decoracoes",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-31",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 224,
    "Title": "Doces Bárbaros",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-31",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/doces-barbaros/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/doces-barbaros.jpg",
    "Image Title": "doces barbaros",
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/doces-barbaros.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "doces-barbaros",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-31",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 226,
    "Title": "Sicoob Crediempar",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-31",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/sicoob-crediempar/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/sicoob_crediempar.jpg",
    "Image Title": "sicoob_crediempar",
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/sicoob_crediempar.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "sicoob-crediempar",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-31",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 228,
    "Title": "Gabarito",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-31",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/gabarito/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/gabarito.jpg",
    "Image Title": "gabarito",
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/gabarito.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "gabarito",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-31",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 230,
    "Title": "Sabin",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-31",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/sabin/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/sabin.jpg",
    "Image Title": "sabin",
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/sabin.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "sabin",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-31",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 232,
    "Title": "Iso Olhos",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-31",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/iso-olhos/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/iso-1.jpg",
    "Image Title": "iso|iso",
    "Image Caption": "|",
    "Image Description": "|",
    "Image Alt Text": "|",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/iso-1.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "iso-olhos",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-31",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 235,
    "Title": "D'Ville",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-31",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/dville/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/dville.jpg",
    "Image Title": "dville",
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/dville.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "dville",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-31",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 237,
    "Title": "Cajubá Country Club",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-31",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/cajuba-country-club/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/cajuba.jpg",
    "Image Title": "cajuba",
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/cajuba.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "cajuba-country-club",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-31",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 239,
    "Title": "Unimed Ituiutaba",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-31",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/unimed-ituiutaba/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/unimed-ituiutaba.jpg",
    "Image Title": "unimed ituiutaba",
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/unimed-ituiutaba.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "unimed-ituiutaba",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-31",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 241,
    "Title": "Unimed",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-31",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/unimed/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/unimed.jpg",
    "Image Title": "unimed",
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/unimed.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "unimed",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-31",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  },
  {
    "ID": 243,
    "Title": "Arantes",
    "Content": "",
    "Excerpt": "",
    "Date": "2020-05-31",
    "Post Type": "clientes",
    "Permalink": "https://wplucianamara1.websiteseguro.com/clientes/arantes/",
    "Image URL": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/arantes.jpg",
    "Image Title": "arantes",
    "Image Caption": "",
    "Image Description": "",
    "Image Alt Text": "",
    "Image Featured": "https://wplucianamara1.websiteseguro.com/wp-content/uploads/2020/05/arantes.jpg",
    "Attachment URL": "",
    "Status": "publish",
    "Author ID": 1,
    "Author Username": "webmaster",
    "Author Email": "contato@sergiooak.com.br",
    "Author First Name": "",
    "Author Last Name": "",
    "Slug": "arantes",
    "Format": "",
    "Template": "",
    "Parent": 0,
    "Parent Slug": 0,
    "Order": 0,
    "Comment Status": "closed",
    "Ping Status": "closed",
    "Post Modified Date": "2020-05-31",
    "Texto bortão": "",
    "link botão": "",
    "ordem": "",
    "Personalizavel": "",
    "Miniatura": ""
  }
]
    }
  },
  computed: {

  },
  mounted() {

  }
}
</script>

<style lang="css" scoped>
</style>
